name: Python CI
#comment 3
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
  # Add step to install dependencies
    - name: Install dependencies
      run: pip install pytest
    - name: Run tests
      run: pytest #bad_code.py
      working-directory: exercise_2
  lint:
  # Complete the lint job configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install flake8
      run: pip install flake8
    - name: Check code format
      run: flake8 #bad_code.py
    - name: Install black
      run: pip install black
    - name: Use black
      run: black #bad_code.py
      working-directory: exercise_2

