name: Docker CD Pipeline
#comment
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      # Add more steps here
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  # More jobs can be added 
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: exercise_3
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest